default: &default
  adapter: postgresql
  encoding: unicode
  username: CubeNews
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: 1password!

development:
  <<: *default
  database: CubeNews_development
  host: localhost
  pool: 5

test:
  <<: *default
  database: CubeNews_test
  host: localhost
  pool: 5

production:
  <<: *default
  database: CubeNews_production
  username: CubeNews
  password: <%= ENV['CUBENEWS_DATABASE_PASSWORD'] %>
